export const INITIAL_ACTIONS = 'INITIAL_ACTIONS';
export const SECOND_ACTION = 'SECOND_ACTION';
export const CHANGE_NAME = 'CHANGE_NAME';
export const HANDLE_FIRST_NUMBER = 'HANDLE_FIRST_NUMBER';
export const HANDLE_SECOND_NUMBER = 'HANDLE_SECOND_NUMBER';
export const SUM_FIRST_SECOND = 'SUM_FIRST_SECOND';